=== docker-practice/miniprogram/schema/page.json
{"type":"object","properties":{"navigationBarBackgroundColor":{"type":"string"},"navigationBarTextStyle":{"enum":["black","white"],"type":"string"},"navigationBarTitleText":{"type":"string"},"navigationStyle":{"enum":["custom","default"],"type":"string"},"backgroundColor":{"type":"string"},"backgroundTextStyle":{"enum":["dark","light"],"type":"string"},"enablePullDownRefresh":{"type":"boolean"},"onReachBottomDistance":{"type":"number"},"disableScroll":{"type":"boolean"},"disableSwipeBack":{"type":"boolean"},"backgroundColorTop":{"type":"string"},"backgroundColorBottom":{"type":"string"},"usingComponents":{"type":"object","additionalProperties":{"type":"string"}},"pageOrientation":{"enum":["auto","landscape","portrait"],"type":"string"},"restartStrategy":{"enum":["homePage","homePageAndLatestPage"],"type":"string"},"component":{"type":"boolean"},"componentGenerics":{"type":"object","additionalProperties":{"anyOf":[{"type":"object","additionalProperties":{"type":"string"}},{"type":"boolean"}]}},"singlePage":{"type":"object","properties":{"navigationBarFit":{"enum":["float","squeezed"],"type":"string"}},"additionalProperties":false},"pageJSONLight":{"$ref":"#/definitions/IOriginalPageJSON"},"pageJSONDark":{"$ref":"#/definitions/IOriginalPageJSON"}},"additionalProperties":false,"definitions":{"IOriginalPageJSON":{"type":"object","properties":{"navigationBarBackgroundColor":{"type":"string"},"navigationBarTextStyle":{"enum":["black","white"],"type":"string"},"navigationBarTitleText":{"type":"string"},"navigationStyle":{"enum":["custom","default"],"type":"string"},"backgroundColor":{"type":"string"},"backgroundTextStyle":{"enum":["dark","light"],"type":"string"},"enablePullDownRefresh":{"type":"boolean"},"onReachBottomDistance":{"type":"number"},"disableScroll":{"type":"boolean"},"disableSwipeBack":{"type":"boolean"},"backgroundColorTop":{"type":"string"},"backgroundColorBottom":{"type":"string"},"usingComponents":{"type":"object","additionalProperties":{"type":"string"}},"pageOrientation":{"enum":["auto","landscape","portrait"],"type":"string"},"restartStrategy":{"enum":["homePage","homePageAndLatestPage"],"type":"string"},"component":{"type":"boolean"},"componentGenerics":{"type":"object","additionalProperties":{"anyOf":[{"type":"object","additionalProperties":{"type":"string"}},{"type":"boolean"}]}},"singlePage":{"type":"object","properties":{"navigationBarFit":{"enum":["float","squeezed"],"type":"string"}},"additionalProperties":false}},"additionalProperties":false}},"$schema":"http://json-schema.org/draft-07/schema#","$version":1587371684236}

=== docker-practice/miniprogram/client/pages/docker/content/index.json
{
  "usingComponents": {
    "i-drawer": "/src/ui/iviewui/dist/drawer/index",
    "i-tab-bar": "/src/ui/iviewui/dist/tab-bar/index",
    "i-tab-bar-item": "/src/ui/iviewui/dist/tab-bar-item/index",
    "i-notice-bar": "/src/ui/iviewui/dist/notice-bar/index",
    "i-button": "/src/ui/iviewui/dist/button/index",
    "i-spin": "/src/ui/iviewui/dist/spin/index",
    "markdown": "/wx-markdown/component/index",
    "wemark": "/wemark/wemark"
  },
  "enablePullDownRefresh": true,
  "backgroundColor": "#36a1f0",
  "navigationStyle": "custom"
}

=== docker-practice/miniprogram/client/pages/docker/content/content.json
{
  "usingComponents": {
    "i-drawer": "/iviewui/dist/drawer/index",
    "i-tab-bar": "/iviewui/dist/tab-bar/index",
    "i-tab-bar-item": "/iviewui/dist/tab-bar-item/index",
    "i-notice-bar": "/iviewui/dist/notice-bar/index",
    "i-button": "/iviewui/dist/button/index",
    "i-spin": "/iviewui/dist/spin/index"
  },
  "enablePullDownRefresh": true,
  "backgroundColor": "#36a1f0",
  "navigationStyle": "custom"
}

=== docker-practice/miniprogram/client/pages/index/index.json
{
  "usingComponents": {
    "i-cell-group": "/src/ui/iviewui/dist/cell-group/index",
    "i-cell": "/src/ui/iviewui/dist/cell/index",
    "i-switch": "/src/ui/iviewui/dist/switch/index",
    "i-panel": "/src/ui/iviewui/dist/panel/index",
    "i-rate": "/src/ui/iviewui/dist/rate/index"
  },
  "navigationStyle": "default",
  "enablePullDownRefresh": true,
  "backgroundTextStyle": "light",
  "backgroundColor": "@bgColor"
}
